# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "http" {
    config = {
      address        = "https://gitlab.com/api/v4/projects/39120322/terraform/state/applications"
      lock_address   = "https://gitlab.com/api/v4/projects/39120322/terraform/state/applications/lock"
      unlock_address = "https://gitlab.com/api/v4/projects/39120322/terraform/state/applications/lock"
      lock_method    = "POST"
      unlock_method  = "DELETE"
      retry_wait_min = "5"
    }
  }
}
