# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "http" {
    address        = "https://gitlab.com/api/v4/projects/53191844/terraform/state/foundation"
    lock_address   = "https://gitlab.com/api/v4/projects/53191844/terraform/state/foundation/lock"
    unlock_address = "https://gitlab.com/api/v4/projects/53191844/terraform/state/foundation/lock"
    lock_method    = "POST"
    unlock_method  = "DELETE"
    retry_wait_min = "5"
  }
}
